-- `incidents` NO es append-only ⇒ cerrar por UPDATE devuelve la fase a idle.
-- Se cierran TODOS los abiertos del sitio: desde T-6.18 cada corrida de
-- `crisis` abre uno nuevo, así que cerrar solo el último dejaría cola.
-- ⚠️ [T-7.51] `closed_at` NO es opcional. Sin él, este UPDATE dejaba filas con
-- `state='closed'` y la hora en nulo, y el dictamen imprime «CIERRE: EN CURSO»
-- cuando ese campo falta: el papel pericial de un incidente cerrado afirmaba que
-- seguía abierto. Se midieron TRES así en la nube dev el 2026-09-17, y una de
-- ellas era un incidente REAL ingerido de `gw-dev-0001`.
--
-- [T-7.52] El sitio por defecto ya NO es el de Puebla: es `site-e2e-900`, y
-- `guarda.sql` aborta contra cualquier sitio que tenga gabinete. Esta línea ya no
-- puede cerrar incidentes de operación.
--
-- ⚠️ [T-7.55] EL CIERRE VA RETRODATADO, y no es un truco: desde que la
-- autorización de reingreso sobrevive al cierre durante `reentry_declare_s` (8 h),
-- un `reset` con `closed_at = now()` dejaría el sitio diciendo «REINGRESO
-- AUTORIZADO» toda esa ventana — o sea, `reset` dejaría de resetear. Y no se puede
-- borrar el dictamen: `dictamens` es append-only a propósito. Retrodatar el cierre
-- es decir lo que de verdad se quiere decir: «esto ya es historia vieja».
-- Los 30 días tienen que superar la ventana, y que no se separen lo comprueba
-- `test_la_ventana_de_reingreso_no_se_separa_del_ajuste`.
UPDATE incidents SET state = 'closed', closed_at = now() - interval '30 days'
 WHERE site_id = :'site'::uuid AND state <> 'closed';
